# Generated by Django 4.0.5 on 2022-12-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('Ville', models.CharField(max_length=250)),
                ('local', models.CharField(max_length=250)),
                ('heureOuverture', models.CharField(choices=[('08H30', '08H30')], default='08H30', max_length=200)),
                ('heureFermeture', models.CharField(choices=[('15H30', '15H30'), ('11H30', '11H30')], max_length=200)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=120, verbose_name='Email Adress')),
                ('mote_de_passe', models.CharField(max_length=250)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Autres', 'Autres')], default='Masculin', max_length=20)),
                ('numero_Compte', models.CharField(max_length=250)),
                ('typeCompte', models.CharField(choices=[('Epargne', 'Epargne'), ('Courant', 'Courant'), ('Autres', 'Autres')], default='Courant', max_length=20)),
                ('fonction', models.CharField(max_length=250)),
                ('numeroTelephone', models.CharField(blank=True, max_length=250, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('Adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Autres', 'Autres')], default='Masculin', max_length=20)),
                ('Adresse', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('numeroTelephone', models.CharField(blank=True, max_length=250, null=True)),
                ('disponibilite', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV_App.agence')),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeProbleme', models.CharField(choices=[('Compte Bloqué', 'Compte Bloqué'), ('Autres', 'Autres')], max_length=200)),
                ('horaire', models.CharField(choices=[('08H45-09H00', '08H45-09H00'), ('11H00-11H15', '11H00-11H45'), ('12H30-12H45', '12H30-12H45')], max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV_App.client')),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV_App.gestionnaire')),
            ],
        ),
    ]
