# Generated by Django 4.0.5 on 2022-12-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV_App', '0002_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('agence', models.ManyToManyField(blank=True, related_name='user_com', to='RV_App.agence')),
            ],
        ),
    ]
